name: Alessia's workflow
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TERM: dumb
    steps:
      - uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 15
      - name: Build
        run: ./gradlew clean build

